### ISSUE TITLE
Youtube not working on Web

### ISSUE THREAD

**Issue by faslurrajah** [ponnamkarthik/ext_video_player#1]
Shows this error

```
Error: PlatformException(MEDIA_ERR_SRC_NOT_SUPPORTED, No further diagnostic information can be determined or provided., The video has been found to be unsuitable (missing or in a format not supported by your browser).)


    at Object.createErrorWithStack (http://localhost:51512/dart_sdk.js:4353:12)
    at Object._rethrow (http://localhost:51512/dart_sdk.js:37629:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:51512/dart_sdk.js:37623:13)
    at Object._microtaskLoop (http://localhost:51512/dart_sdk.js:37455:13)
    at _startMicrotaskLoop (http://localhost:51512/dart_sdk.js:37461:13)
    at http://localhost:51512/dart_sdk.js:32980:9
```

**Comment by ponnamkarthik** [comment]
@faslurrajah Fixed in newer version

**Comment by SebastianKumor** [comment]
I still get this issue. Is this because of some video settings ?

**Comment by ponnamkarthik** [comment]
Can you @SebastianKumor give me the link you are testing with

**Comment by SebastianKumor** [comment]
@ponnamkarthik  this one for example gives me this error https://www.youtube.com/watch?v=3DY_WDaaK9w

**Comment by radvansky-tomas** [comment]
It cannot work, as you replaced logic for gathering video URL with this new plugin ...which has no support for web
https://github.com/Hexer10/youtube_explode_dart/issues/16

I suggest to either fix it there or downgrade
